services:
  pnotify:
    image: pnotify
    container_name: pnotify
    environment:
      - FILEPATH=/tmp/gluetun
      - BASEURL=http://gluetun:8080
      - RUST_LOG=info # info or debug
    restart: unless-stopped